name: hydrus
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.1
  delayed_widget: ^1.1.1
  # flutter_screenutil: ^5.0.0+2
  smooth_page_indicator: ^1.0.0+2  
  form_builder_validators: ^8.1.1
  flutter_hooks: ^0.18.3
  flutter_form_builder: ^7.1.1
  google_fonts: ^2.1.0
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.1.1
  getwidget: ^2.0.5
  device_preview: ^1.0.0
  get: ^4.6.1
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^1.4.0
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  persistent_bottom_nav_bar: ^4.0.2
  modal_bottom_sheet: ^2.0.1
  intl_phone_field: ^3.1.0
  dropdown_search: ^4.0.0
  font_awesome_flutter: ^10.1.0
  material_design_icons_flutter: ^5.0.6996
  dio: ^4.0.6
  authentication_repository:
    path: packages/authentication_repository

  user_repository:
    path: packages/user_repository
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  file_picker: ^4.6.1
  open_file: ^3.2.1
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2
  provider: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.0
  local_auth: ^2.1.2
  jiffy: ^5.0.0
  formz: ^0.4.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
    
jsonToDart: 
  nullSafety: true
  nullValueDataType: String #default: dynamic

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - .env
  # fonts: 
   